export const team = [
    {
        Name: 'Engineering',
        Description:
            'There are three subteams of Engineering: Web Development, Algorithms, and Data Analysis. The Web Dev subteam builds the front-end and back-end of the Perfect Match website. The Algorithms subteam improves the matching algorithm that matches students based on their preferences. The Data Analysis subteam analyzes and visualizes the data collected from the Perfect Match survey.',
        Members: [
            {
                Name: 'Nicholas Varela',
                ClassYear: 2025,
                Major: 'CS & Public Policy',
                Img: '/members/nick.jpg',
                Linkedin: 'https://www.linkedin.com/in/nicholas-varela',
                Title1: 'Engineering Team Co-Lead',
                Title2: 'Web Dev Subteam Head',
            },
            {
                Name: 'Pratyush Sudhakar',
                ClassYear: 2025,
                Major: 'CS & Math',
                Img: '/members/pratyush.jpg',
                Team: 'Engineering',
                Linkedin: 'https://www.linkedin.com/in/pratyushsudhakar',
                Title1: 'Engineering Team Co-Lead',
                Title2: 'Web Dev Member',
            },
            {
                Name: 'Flavia Jiang',
                ClassYear: 2025,
                Major: 'Info Sci & Stats',
                Img: '/members/flavia.jpg',
                Title1: 'Data Analysis Subteam Head',
                Title2: 'Web Dev Member',
            },
            {
                Name: 'Taerim Eom',
                ClassYear: 2024,
                Major: 'CS',
                Img: '/members/taerim.jpg',
                Linkedin: 'https://www.linkedin.com/in/taerim-eom-301a41197',
                Title1: 'Algorithms Subteam Head',
            },
            {
                Name: 'Vipin Gunda',
                ClassYear: 2025,
                Major: 'CS & Math',
                Img: '/members/vipin.jpg',
                Linkedin: 'https://www.linkedin.com/in/vipin-gunda',
                Title1: 'Algorithms Subteam Member',
            },
            {
                Name: 'Daniel Chuang',
                ClassYear: 2026,
                Major: 'CS & Math & Government',
                Img: '/members/daniel.png',
                Linkedin: 'https://www.linkedin.com/in/daniel-chuang-7a1bb920b/',
                Title1: 'Data Analysis Subteam Member',
            },
            {
                Name: 'Samantha Smith',
                ClassYear: 2026,
                Major: 'Information Science',
                Img: '/members/sam.jpeg',
                Linkedin:
                    'https://www.linkedin.com/in/samantha-smith-057302251/?profileId=ACoAAD4owcMBUJd9F2pVXmgf5ClwGk_KIu2gmrM/',
                Title1: 'Web Dev Subteam Member & Designer',
            },
        ],
    },
    {
        Name: 'Business',
        Description:
            'The Business team is responsible for marketing Perfect Match and reaching out to potential sponsors.',
        Members: [
            {
                Name: 'Grace Wilkey',
                ClassYear: 2024,
                Major: 'Hospitality Administration',
                Img: '/members/grace.jpg',
                Linkedin: 'https://www.linkedin.com/in/grace-wilkey-201a30147',
                Title1: 'Business Team Lead',
            },
            {
                Name: 'Varshini Madhavan',
                ClassYear: 2025,
                Major: 'Industrial and Labor Relations',
                Img: '/members/varshini.jpg',
                Linkedin: 'https://www.linkedin.com/in/varshinimadhavan',
                Title1: 'Business Team Member',
            },
            {
                Name: 'Kelly Hong',
                ClassYear: 2027,
                Major: 'Fine Arts',
                Img: '/members/kelly.png',
                Linkedin: 'https://www.linkedin.com/in/kelly-hong-64666b294/ ',
                Title1: 'Designer',
            },
        ],
    },
];
